### ISSUE TITLE
Ajout d'une fonction d'argent qui se génère

### ISSUE THREAD

**Issue by MrKaaaa** [GinierClasses/teamproject-indecis-gang#4]
Variable d'argent qui se génère avec le temps

L'argent se génère grâce a une troupe qu'on pose (Comme les tournesol dans plant vs zombie)

Affichage sur la fenêtre avec un compteur

-- L'argent a un seuil maximum (pour ne pas trop en accumuler) 
Le seuil est automatiquement augmenté lors d'un passage à niveau --

**Comment by RuCaVi** [comment]
Ce serait bien qu'il n'y ait pas de maximum d'argent, car même si le joueur attends que l'argent s'accumule, il en aura pour un moment avant que cela devienne cheater. De plus s'il y a pas de maximum, cela pourrait donner des games fun.
